<?php $user_id = Session::getInstance()->getUser()->id ;
            $user = User::userData($user_id);



?>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link"
                   href="<?php echo App::config("url") ?>">Home </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link"
                   href="<?php echo App::config("url") . "admin/logout" ?>">Logout <?php echo Session::getInstance()->getUser()->name ?></a>
            </li>

        </ul>

    </div>
</nav>


<h3>Current user data</h3>
Profile image<br>
<?php if($user->getImage()):?>
    <img class="card-img-top" src="<?php echo App::config('url').'app/img/'.$user->getImage(); ?>">

<?php else:?>
    <img src="<?php echo App::config('url').'app/view/barcode.php?size=100&text='.$user->getId() . $user->getfirstname()?>">

<?php endif;?><br><hr>


First Name: <?php echo $user->firstname; ?><br><hr>
Last name: <?php echo $user->lastname; ?><br><hr>
Email: <?php echo $user->email; ?><br><hr>


    <form method="post" action="<?php echo App::config('url') ?>Admin/updateImage"
          enctype="multipart/form-data">
        <div class="form-group">
            <label for="image">Change image</label>
            <input type="file" name="image" id="image">
            <input type="hidden" name="post_id" id="post_id" value="<?php echo $user_id; ?>"/>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>

<form method="post" action="<?php echo App::config('url') ?>admin/updateInfo">
    <h2>Change your user data</h2>
    <div class="form-group">

        <label for="firstname">First name</label>
        <input type="firstname" name="firstname">


        <label for="lastname">Last name</label>
        <input type="lastname" name="lastname">

        <label for="email">Email</label>
        <input type="email" name="email">


        <input type="hidden" name="post_id" id="post_id" value="<?php echo $user_id; ?>"/>

    </div>

    <button type="submit" class="btn btn-primary">Edit data</button>

</form>

<?php if (isset($message)): echo $message ?>
<?php endif;?>


    <form method="post" action="<?php echo App::config('url') ?>admin/updatePass">
        <h2>Change your Password</h2>
        <div class="form-group">

            <label for="new_password">Password</label>
            <input type="password" name="new_pass">

            <label for="new_password_conf">Confirm password</label>
            <input type="password" name="new_pass_conf">

            <input type="hidden" name="post_id" id="post_id" value="<?php echo $user_id; ?>"/>

        </div>

        <button type="submit" class="btn btn-primary">Change</button>

    </form>
<?php if (isset($pass_msg)): echo $pass_msg ?>
<?php endif;?>



