<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta charset="UTF-8">
        <title>Inchoo PHP Academy 2019</title>
        <script src="<?php echo App::config('url');?>assets/jquery-3.3.1.slim.min.js"></script>
        <link rel="stylesheet" href="<?php echo App::config('url');?>assets/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo App::config('url');?>assets/style.css">
        <script src="<?php echo App::config('url');?>assets/bootstrap/js/bootstrap.js"></script>
    </head>
</head>
<body>
    <?php echo $content ?>
</body>
</html>