<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta charset="UTF-8">
        <title>Inchoo PHP Academy 2019</title>
        <script src="<?php echo App::config('url');?>assets/jquery-3.3.1.slim.min.js"></script>
        <link rel="stylesheet" href="<?php echo App::config('url');?>assets/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="<?php echo App::config('url');?>assets/style.css">
        <script src="<?php echo App::config('url');?>assets/bootstrap/js/bootstrap.js"></script>
        <script src="<?php echo App::config('url');?>assets/javascript.js"></script>
    </head>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <?php echo $content ?>
</body>
</html>