<a href="<?php echo App::config("url") ?>">Index</a><hr />

<?php if( Session::getInstance()->isLoggedIn() &&
    $post->getUserid()==Session::getInstance()->getUser()->id): ?>
<a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete posts (and all likes and comments</a><br />
<?php endif; ?>

<cite><?= htmlspecialchars($post->getUser()) ?></cite>  <?php echo $post->date ?>
<p><?= htmlspecialchars($post->getContent()) ?></p> Likes: <?php echo $post->getLikes() ?>


<h3>Comments</h3>
<?php foreach ($post->getComments() as $comment): ?>
    <p>
        <cite><?= htmlspecialchars($comment->user) ?></cite>
        <?php echo $comment->date ?><br />
        <?php echo $comment->content ?>
    </p>
<?php endforeach; ?>

<h3>Tags</h3>
<?php foreach ($post->getTags() as $tag): ?>
    <p style="margin-left: 20px;">
        <cite><?= htmlspecialchars($tag->content) ?></cite>
    </p>
    <hr />
<?php endforeach; ?>

<h3>Likes</h3>
<?php foreach ($likes as $like): ?>

    <p><?php echo $like->user; ?></p>
    <?php if ($user->getAdmin() === '1'): ?>
        <a href="<?php echo App::config('url') ?>admin/deleteLike/<?php echo $post->id . ',' . $like->unique_likes ?>">Delete Like</a>
    <?php endif; ?>

<?php endforeach;?>


<?php if( Session::getInstance()->isLoggedIn() ): ?>

<form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

<div class="form-group">
        <label for="content">New comment</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
<?php endif; ?>

<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<div class="fb-share-button" data-href="http://phpakademija.loc/InchooPHPAkademijaZ7/Index/view/<?php echo $post->getId() ?>" data-layout="button" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fphpakademija.loc%2FInchooPHPAkademijaZ7%2FIndex%2Fview%2F17&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>

<a href="https://plus.google.com/share?url=<?php echo App::config('url') ?>Index/view/<?php echo $post->id?>" onclick="javascript:window.open(this.href,
  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img
            src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+"/></a>