<a href="<?php echo App::config("url") ?>">Index</a><hr />

<?php if( Session::getInstance()->isLoggedIn() &&
    $post->getUserid()==Session::getInstance()->getUser()->id): ?>
<a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete posts (and all likes and comments</a><br />
<?php endif; ?>

<cite><?= htmlspecialchars($post->getUser()) ?></cite>  <?php echo $post->date ?>
<p><?= htmlspecialchars($post->getContent()) ?></p> Likes: <?php echo $post->getLikes() ?>


<h3>Comments</h3>
<?php foreach ($post->getComments() as $comment): ?>
    <p>
        <cite><?= htmlspecialchars($comment->user) ?></cite>
        <?php echo $comment->date ?><br />
        <?php echo $comment->content ?>
    </p>
<?php endforeach; ?>

<h3>Tags</h3>
<?php foreach ($post->getTags() as $tag): ?>
    <p style="margin-left: 20px;">
        <cite><?= htmlspecialchars($tag->content) ?></cite>
    </p>
    <hr />
<?php endforeach; ?>

<h3>Likes</h3>
<?php foreach ($likes as $like): ?>

    <p><?php echo $like->user; ?></p>
    <?php if ($user->getAdmin() === '1'): ?>
        <a href="<?php echo App::config('url') ?>admin/deleteLike/<?php echo $post->id . ',' . $like->unique_likes ?>">Delete Like</a>
    <?php endif; ?>

<?php endforeach;?>


<?php if( Session::getInstance()->isLoggedIn() ): ?>

<form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

<div class="form-group">
        <label for="content">New comment</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
<?php endif; ?>


